infobloxopen/terraform-provider-infoblox

infoblox/provider.go, infoblox/resourceIPAllocation.go, infoblox/resourceIPAssociation.go, infoblox/resourceNetwork.go, infoblox/resourceNetworkView.go
This commit also contains changes in the way IP gets assigned.
Previously the IP assigned was of type fixedaddress
now it has become host address
Necessary changes in other resources have been made
to allocate host address
=> This commit contains a new resource IPAssociation

README.md
As some of our customers have been using the Product without a CNA license. We will have to create the EAs manually for this to work
=> Updated Readme for use case without CNA license

infoblox/resource_infoblox_network.go, infoblox/resource_infoblox_network_test.go
NIOS convert parent network to network container when network
inserted into network.
After such convertion caused parent network ID changed to network
container ID, so parent will be unavailable to terraform.
To prevent it - add check that parent is network container before
network allocation.
=> Check that parent exists before network allocation.

GNUmakefile
Removing `website` and `website-test` from GNUmakefile.
Do not see it being used any where in the code.
Also could observe the website [https://github.com/hashicorp/terraform-website](url) build failing.
=> removing website and website-test from GNUmakefile

.travis.yml, GNUmakefile
Removing `website` and `website-test` from GNUmakefile.  #125 for `develop` branch.
=> removing unused code related to website

README.md, docs/DEVELOPMENT.md, docs/USING.md
To make the things simple for users and developers, have made bit of restructuring of existing README.md file content.
Added 2 independent sections as DEVELOPMENT and USING and they will be added as new files under doc folder. A reference of these sections would be provided from README.
Since the development and validation of existing content in GitHub repo was done with Golang v1.12.x and Terraform v0.11.x the content has been aligned to that.
=> updating the doc for developing and using the plugin

infoblox/provider.go, infoblox/resource_infoblox_a_record.go, infoblox/resource_infoblox_aaaa_record.go, infoblox/resource_infoblox_cname_record.go, infoblox/resource_infoblox_ptr_record.go, infoblox/resource_infoblox_ptr_record_test.go, vendor/github.com/infobloxopen/infoblox-go-client/object_manager.go, vendor/github.com/infobloxopen/infoblox-go-client/objects.go
This PR fixes UPDATE functionality of A, AAAA and PTR record. 
With this changes, the update operation when a CIDR is given for all the records would behave as below,
1. Use next available IP feature and get an IP and create a record using allocated IP.
2. When update operation is called check if CIDR is changed,
- If not changed then do not again use next available IP feature to get a new IP.
- If changed then get a new IP and use this IP to update the record
Allow to create a record with an TTL value of 0
=> Fix TTL and Update functions

examples/v0.14/AWS/AllocationAndAssociation/infoblox.tf, examples/v0.14/Azure/NetworkContainer/IPv4/infoblox.tf, examples/v0.14/Azure/NetworkContainer/IPv6/infoblox.tf, examples/v0.14/Azure/NextAvailableNetwork/infoblox.tf, examples/v0.14/VMWare/AllocationAndAssociation/infoblox.tf, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_ip_allocation_test.go, infoblox/resource_infoblox_ip_association.go, infoblox/resource_infoblox_ip_association_test.go, vendor/github.com/infobloxopen/infoblox-go-client/object_manager.go
Fixes some important bugs. Below are the list of the same,
- "host_name" field is not mandatory while Creating of Fixed address object
- Difference in behavior for Host record update for the dynamic IP address allocation
- Need to support ttl field for DNS Host record object
- TTL value is not setting to Zero in the Created records
- Terraform update for Fixed address "ip-addr" is not working
- Resources not deleting when a leading or trailing space are specified in network view value under a resource group
Solves #50
=> bug fixes on host and fixed address rec

infoblox/datasource_infoblox_a_record_test.go, infoblox/datasource_infoblox_cname_record_test.go, infoblox/resource_infoblox_a_record_test.go, infoblox/resource_infoblox_aaaa_record_test.go, infoblox/resource_infoblox_cname_record_test.go, infoblox/resource_infoblox_ip_allocation_test.go, infoblox/resource_infoblox_ip_association_test.go, infoblox/resource_infoblox_ptr_record_test.go
With this PR we are a uniform zone across  the UTs. `test.com` is the zone which needs to be created while running the UTs.
=> creating a uniform zone accorss UTs

README.md
From now on there would no more `develop` branch. Developers can directly raise a PR on `master` branch.
=> Removing develop branch

infoblox/resource_infoblox_ip_association_legacy.go
`infoblox_ipv6_association` resource is expecting `infoblox_ip_association` resource parameters. Correcting the same.
=> association with host record bug fix

infoblox/provider.go
* When the user doesn't export the `INFOBLOX_PASSWORD` env var, the terraform client is prompting the user for input, which 
is not hidden in any way.
* We decided to disable the cli input to reduce the chance of the password gets compromised.
* Related terraform issue: https://github.com/hashicorp/terraform/issues/29609
* Made the password parameter optional.
* providerConfigure function will raise an error if password parameter is
not set.
* This way, terraform cli will not ask a user for the password.
* Now, the only two ways to set the API key parameter is to export `INFOBLOX_PASSWORD` env var, or to [configure the 'password' 
parameter](https://www.terraform.io/language/providers/configuration#provider-configuration-1) in the provider configuration section of the terraform root `.tf` …
=> Disabled cli input for the password provider parameter

infoblox/resource_infoblox_network_container.go, infoblox/resource_infoblox_network_container_test.go
This adds both test cases to test that error is thrown for `cidr` value changes,  and fixes no error is thrown for `cidr` changes. 
This has additional commit than the PR #300
=> Adds test cases and fixes no error is thrown for 'cidr' changes

docs/data-sources/infoblox_txt_record.md, docs/resources/infoblox_txt_record.md, examples/datasources/infoblox_txt_record.tf, examples/resources/infoblox_txt_record.tf
Updated text parameter description.
Updated resource and data-source examples.
=> Updated documentation for TXT-Record

infoblox/provider.go, infoblox/resource_infoblox_network_view.go
[FIX] Handle ext_attrs from panic when Null, Network view ext_attrs idempotent for each apply.
[IMP] Remove "Terraform Internal ID" from the ext_attrs from state file.
=> Manage ext_attrs for NULL value and State File

infoblox/datasource_infoblox_host_record.go, infoblox/datasource_infoblox_host_record_test.go, infoblox/datasource_infoblox_ipv6_network_container.go, infoblox/datasource_infoblox_network.go, infoblox/datasource_infoblox_network_test.go, infoblox/provider.go
Added data source for ipv6 network, ipv6 network container and host record.
=> Added data source for ipv6 network, ipv6 network container and host record

go.mod, infoblox/datasource_infoblox_host_record.go
Fix | NIOS-101231 | Added enable dns to return fields.
- **both False**
```
host_rec_res = {
"filters" = tomap({
"name" = "host1.example1.org"
})
"id" = "1718100618"
"results" = tolist([
{
"comment" = ""
"dns_view" = " "
"duid" = "12:00:43:fe:9a:81"
"enable_dhcp" = false
"enable_dns" = false
"ext_attrs" = "{\"Terraform Internal ID\":\"0cd6038b-a6f8-4097-988e-1217184e3c39\"}"
"fqdn" = "host1.example1.org"
"id" = "record:host/ZG5zLmhvc3QkLm5vbl9ETlNfaG9zdF9yb290LjAuMTcxODA3MzI0MTc1OC5vcmcuZXhhbXBsZTEuaG9zdDE:host1.example1.org/%20"
"ipv4_addr" = "10.10.0.7"
"ipv6_addr" = "1::1"
"mac_addr" = "12:00:43:fe:9a:8c"
"ttl" = -2147483648
"zone" = ""
},
])
}
```
- **DNS-true & DHCP-false**
```host_rec_res = {
"filters" = tomap({
"name" = "host1.example1.org"
})
"id" = "1718100596"
"results" = …
```
=> Fix | NIOS-101231 | Added enable dns to return fields.

infoblox/resource_infoblox_a_record.go, infoblox/resource_infoblox_a_record_test.go, infoblox/resource_infoblox_aaaa_record_test.go
test case for a record next available ip
=> Test cases for a record next-available-ip 

infoblox/resource_infoblox_ip_allocation.go
Fix for Npa 193
Failed to update host record: Invalid view value caused by trailing whitespace when enabling DNS
=> Fix for Npa 193- Failed to update host record: Invalid view value caused by trailing whitespace when enabling DNS

infoblox/resource_infoblox_aaaa_record.go, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_ip_association.go
- Added handling of ip_address_type field for host record.
- Added disable field for Host record.
=> bugFix for hostRecord ip_addr_type and disable fields

infoblox/resource_infoblox_ip_allocation_test.go, infoblox/resource_infoblox_network_container_test.go
Host record : 
Added test cases for IPV4 ,IPV6 and both for host record for next available ip
Network container 
Added test cases for next_Available ip
=> test cases for host record and network container for next available IP

infoblox/resource_infoblox_ip_allocation.go
Fix for NPA-208 - > Update operation is failing for IPv4 host using terraform
=> Fix for Npa 208

infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_network.go
=> not setting ip_address_type and object fields when filter_params is not used.

infoblox/datasource_infoblox_dtc_lbdn.go, infoblox/datasource_infoblox_dtc_pool.go, infoblox/resource_infoblox_dtc_lbdn.go, infoblox/resource_infoblox_dtc_pool.go, infoblox/resource_infoblox_dtc_pool_test.go
1. NPA-304 Fix: Adding 'availability' and 'quorum' fields in Import and Get function in DTC pool resource
2. NPA-305 Fix: 
- Handling DiffSuppressFunc for consolidated_monitors field when auto_consolidated_monitors and consolidated_monitors fields given and data to be passed to UpdateDtcPool function.
=> NPA-304, 305 Fix
