examples/VMware/README.md, examples/VMware/example.tf
=> Added an example tf for Vmware Vshpere

Gopkg.lock, Gopkg.toml, infoblox/provider.go, infoblox/resourceIPAllocation_test.go, infoblox/resourceIPAssociation.go, infoblox/resourceIPAssociation_test.go, infoblox/resourceNetwork.go, infoblox/resourceNetworkView_test.go, infoblox/resourceNetwork_test.go
=> This commit contains patch to rebase issue

Gopkg.lock, Gopkg.toml, infoblox/provider.go, infoblox/provider_test.go, infoblox/resourceARecord.go, infoblox/resourceCNAMERecord.go, infoblox/resourceIPAllocation.go, infoblox/resourceIPAssociation.go, infoblox/resourceNetwork.go, infoblox/resourcePTRRecord.go, vendor/github.com/infobloxopen/infoblox-go-client/connector.go, vendor/github.com/infobloxopen/infoblox-go-client/lock.go, vendor/github.com/infobloxopen/infoblox-go-client/object_manager.go
removing validation because wapi check the correct version
add ea for CNAME as it was missed and CP needs EA's
made the dependency to latest version
=> Addressing some internal QA bugs

infoblox/provider.go
Instead of adding an option to disable the license check as proposed in #23 i suggest to remove the license check entirely.
=> Remove license check entirely

infoblox/resourceCNAMERecord.go
Modify CNAME resource create function to remove zone suffix for Canonical name . Add zone suffix to alias record if not present.
#60
=> Modify CNAME resource create function to remove zone

examples/datasources/azurerm/README.md, examples/datasources/azurerm/main.tf, infoblox/datasource_infoblox_network.go, infoblox/datasource_infoblox_network_test.go, infoblox/provider.go
=> New datasource infoblox network

README.md
Added Next Available Network documentation content
=> doc change

README.md
merged the same code from 2 different branches
=> Revert "doc change"

.travis.yml, GNUmakefile, README.md, examples/AWS/NextAvailableNetwork/infoblox.tf, examples/AWS/README.md, infoblox/provider.go, infoblox/resource_infoblox_ipv6_network.go, infoblox/resource_infoblox_ipv6_network_test.go
Added support to Create and Delete a IPv6 network.
Added feature to update EAs of created IPv6 network.
=> IPv6 Network support

.github/workflows/release.yml, .goreleaser.yml
Please add before merge the github secrets GPG_PRIVATE_KEY and PASSPHRASE, see more details at:
https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-
=> Add provider to terraform registry

examples/v0.14/Resources/AWS/AllocationAndAssociation/infoblox.tf, examples/v0.14/Resources/Azure/NetworkContainer/IPv4/infoblox.tf, examples/v0.14/Resources/Azure/NetworkContainer/IPv6/infoblox.tf, examples/v0.14/Resources/Azure/NextAvailableNetwork/infoblox.tf, examples/v0.14/Resources/VMWare/AllocationAndAssociation/infoblox.tf, infoblox/datasource_infoblox_a_record_test.go, infoblox/resource_infoblox_a_record_test.go, infoblox/resource_infoblox_aaaa_record_test.go, infoblox/resource_infoblox_cname_record_test.go, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_ip_allocation_test.go, infoblox/resource_infoblox_ip_association.go, infoblox/resource_infoblox_ip_association_test.go, infoblox/resource_infoblox_ptr_record_test.go
With this PR have removed Fixed Address record support in Allocation and Association.
UTs have been modified for the same.
Appropriate tf files have been updated.
=> Removing Fixed Address support

examples/v0.14/DataSources/network.tf, examples/v0.14/DataSources/recordA.tf, examples/v0.14/DataSources/recordCNAME.tf, examples/v0.14/Resources/AAAARecord/infoblox.tf, examples/v0.14/Resources/AWS/AllocationAndAssociation/infoblox.tf, examples/v0.14/Resources/AWS/Network/infoblox.tf, examples/v0.14/Resources/AWS/NetworkContainer/infoblox.tf, examples/v0.14/Resources/AWS/NextAvailableNetwork/infoblox.tf, examples/v0.14/Resources/AWS/PTRRecord/infoblox.tf, examples/v0.14/Resources/Azure/NextAvailableNetwork/terraform.tf, examples/v0.14/Resources/CNAMERecord/infoblox.tf, examples/v0.14/Resources/NetworkView/infoblox.tf, examples/v0.14/Resources/VMWare/AllocationAndAssociation/versions.tf, examples/v0.14/Resources/VMWare/Network/IPv4/versions.tf, examples/v0.14/Resources/VMWare/Network/IPv6/versions.tf, examples/v0.14/Resources/VMWare/NetworkContainer/IPv4/versions.tf, examples/v0.14/Resources/VMWare/NetworkContainer/IPv6/versions.tf, examples/v0.14/Resources/VMWare/NextAvailableNetwork/versions.tf, examples/v0.14/Resources/VMWare/PTRRecord/versions.tf, examples/v0.14/Resources/terraform.tf
=> updating examples to fetch latest version of plugin

infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_ip_allocation_legacy.go, infoblox/resource_infoblox_ip_association_test.go
1) TTL handling for legacy resource infoblox_ipv4/v6_allocation
2) enable_dhcp handling for infoblox_allocation resource (emptying of MAC address and DUID if enable_dhcp=false)
=> Bugfixes 2021-12-20

README.md
Updating the plugin release version to `v2.1.0`
=> Update the release version of plugin

infoblox/datasource_infoblox_a_record.go, infoblox/datasource_infoblox_cname_record.go, infoblox/datasource_infoblox_mx_record.go, infoblox/datasource_infoblox_network.go, infoblox/datasource_infoblox_network_container.go, infoblox/datasource_infoblox_network_container_test.go, infoblox/datasource_infoblox_ptr_record_test.go, infoblox/datasource_infoblox_srv_record.go, infoblox/datasource_infoblox_txt_record.go
1) making 'dns_view' and 'network_view' fields optional for all the data sources
2) fixing wrong 'ext_attrs' handling for 'infoblox_ipv4_network_container' data source
3) adding more tests
=> bugfixes 2023-03-28

CHANGELOG.md, README.md, docs/resources/infoblox_ipv4_network_container.md, docs/resources/infoblox_ipv6_network_container.md
- added the latest version in README file
- added release details in CHANGELOG
- updated ipv4 and ipv6 network container's documentation
=> Updates the CHANGELOG  with latest version

go.mod, go.sum, vendor/github.com/infobloxopen/infoblox-go-client/v2/object_manager_a-record.go, vendor/github.com/infobloxopen/infoblox-go-client/v2/object_manager_aaaa-record.go, vendor/modules.txt
Updating vendor and go.mod dependencies.
=> Updating dependencies for go-client changes

CHANGELOG.md, DEVELOP.md, GETTING.md, README.md, docs/resources/infoblox_a_record.md, docs/resources/infoblox_aaaa_record.md
This PR has release notes in CHANGELOG and other documentation files
=> Updating documentation and release notes CHANGELOG.md

docs/data-sources/infoblox_a_record.md, docs/data-sources/infoblox_aaaa_record.md, docs/data-sources/infoblox_cname_record.md, docs/data-sources/infoblox_dns_view.md, docs/data-sources/infoblox_ipv4_network.md, docs/data-sources/infoblox_ipv4_network_container.md, docs/data-sources/infoblox_mx_record.md, docs/data-sources/infoblox_network_view.md, docs/data-sources/infoblox_ptr_record.md, docs/data-sources/infoblox_srv_record.md, docs/data-sources/infoblox_txt_record.md, docs/data-sources/infoblox_zone_auth.md, docs/resources/infoblox_zone_auth.md, examples/resources/infoblox_zone_auth.tf, infoblox/resource_infoblox_a_record.go, infoblox/resource_infoblox_aaaa_record.go, infoblox/resource_infoblox_cname_record.go, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_mx_record.go, infoblox/resource_infoblox_ptr_record.go, infoblox/resource_infoblox_srv_record.go, infoblox/resource_infoblox_txt_record.go
This PR contains minimal changes of filters description in datasources
=> Updates filters description in datasource docs

CHANGELOG.md, GETTING.md, README.md, docs/data-sources/infoblox_a_record.md, docs/data-sources/infoblox_aaaa_record.md, docs/data-sources/infoblox_cname_record.md, docs/data-sources/infoblox_dns_view.md, docs/data-sources/infoblox_ipv4_network.md, docs/data-sources/infoblox_ipv4_network_container.md, docs/data-sources/infoblox_mx_record.md, docs/data-sources/infoblox_network_view.md, docs/data-sources/infoblox_ptr_record.md, docs/data-sources/infoblox_srv_record.md, docs/data-sources/infoblox_txt_record.md, docs/data-sources/infoblox_zone_auth.md, go.mod, go.sum, vendor/github.com/infobloxopen/infoblox-go-client/v2/CHANGELOG.md, vendor/github.com/infobloxopen/infoblox-go-client/v2/README.md, vendor/modules.txt
=> Updates CHANGELOG file for plugin release

infoblox/provider.go, infoblox/resource_infoblox_a_record.go
=> Added support for Terraform Internal ID EA to RecordA.

infoblox/provider.go, infoblox/resource_infoblox_a_record.go, infoblox/resource_infoblox_cname_record.go, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_ip_association.go, infoblox/resource_infoblox_mx_record.go, infoblox/resource_infoblox_network.go, infoblox/resource_infoblox_network_container.go, infoblox/resource_infoblox_network_view.go
Added new EA Terraform IntrenalID with UUID to identify the resource as unique ID as ref changes on value change
=> Updated A, CNAME, MX, Network, NetworkContainer and NetworkView

infoblox/resource_infoblox_ip_association.go
NIOS-99714 | Fixed Host record import when recored created without mac or uuid.
=> NIOS-99714 | Fixed Host record import when recored created without mac or uuid.

docs/resources/infoblox_ipv6_network.md, examples/resources/infoblox_ipv6_network.tf
[Fix] NIOS-100049 | Updated IPv6 network examples.
=> [Fix] NIOS-100049 | Updated IPv6 network examples.

infoblox/datasource_infoblox_host_record.go
Added support for mac, duid, enable_dhcp, enable_dns for host record data source
=> Added support for mac, duid, enable_dhcp, enable_dns for host record data source

examples/datasources/infoblox_host_record.tf, examples/datasources/infoblox_ipv6_network.tf, examples/datasources/infoblox_ipv6_network_container.tf
Adding example for host record, IPv6 network and container.
=> Adding example for host record, ipv6 network and container.

examples/datasources/infoblox_host_record.tf
added EA search example for host record.
=> added EA search example for host record.

CHANGELOG.md, README.md
Updated changelog.md and readme.md for 2.7.0 release
=> Updated changelog.md and readme.md for 2.7.0 release

infoblox/resource_infoblox_aaaa_record.go, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_network.go, infoblox/resource_infoblox_network_container.go
1. Implement next-available network and network container within a network and network container.
2. Add next-available-ip for RecordAAAA and RecordHost.
=> Next available

infoblox/resource_infoblox_a_record.go
NPA-182
Implement next_available_ip for RecordA in terraform
=> A record implementation for next available ip

infoblox/resource_infoblox_a_record.go, infoblox/resource_infoblox_aaaa_record.go, infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_network_test.go
Adding other fields for host record.
=> adding other fields for host-record

infoblox/resource_infoblox_zone_delegated.go
TypeSet in the schema for delegate_to field changed to TypeList
=> Fix for NPA-155 

infoblox/resource_infoblox_ip_allocation.go
…or dynamic allocation using filter_params
=> NPA-209 Fix: removing ipv4_addr and ipv6_addr fields from statefile for dynamic allocation using filter_params

infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_ip_association.go
DiffSupress function changes for alias field in host record when dns is disabled
=> DiffSupress function changes for alias field in host record when dns is disabled 

infoblox/resource_infoblox_ip_allocation.go, infoblox/resource_infoblox_network.go
=> setting ip_addr_type, object fields to null during import and disable fields.

infoblox/resource_infoblox_a_record.go, infoblox/resource_infoblox_a_record_test.go
correction for the typo in error message for A  record
=> correction for the typo in error message for A  record

infoblox/datasource_infoblox_dtc_pool.go, infoblox/datasource_infoblox_dtc_pool_test.go, infoblox/resource_infoblox_dtc_pool_test.go
1. Test cases for resource DTC pool
2. Test cases for datasource DTC pool
3. Updated datasource_infoblox_dtc_pool.go to retrieve name for preferred and alternate topology
=> test cases for resource and datasource for DTC pool

infoblox/datasource_infoblox_dtc_lbdn.go, infoblox/datasource_infoblox_dtc_pool.go, infoblox/datasource_infoblox_dtc_server.go, infoblox/resource_infoblox_dtc_server.go
- Added error message after Update function in resourcedtcServerUpdate function 
- Updated resourceDtcServerImport function
=> [FIX-NPA-289]  Added error message after Update function in resourcedtcServerUpdate function 

infoblox/datasource_infoblox_dtc_lbdn.go, infoblox/datasource_infoblox_dtc_pool.go, infoblox/datasource_infoblox_dtc_server.go
Added 'health' parameter in DTC object datasources output
=> [FIX]NPA-295 Added 'health' parameter in DTC object datasources output

infoblox/resource_infoblox_dtc_pool.go
Created a function to add default values for invert_monitor_metric , method , monitor_weighing fields in lb_dynamic_ratio_alternate and lb_dynamic_ratio_preferred fields
=> [NPA-297] Added default values for fields in lb_dynamic_ratio_alternate and lb_dynamic_ratio_preferred

infoblox/datasource_infoblox_dtc_lbdn.go, infoblox/datasource_infoblox_dtc_pool.go, infoblox/datasource_infoblox_dtc_server.go
Changed the fields from Optional to Computed in the dataSource Schema for LBDN , Pools and Servers
=> Changed the fields from Optional to Computed in the dataSource Schema

infoblox/resource_infoblox_dtc_lbdn.go, infoblox/resource_infoblox_dtc_pool.go
NPA-299 
- Added default values for lb_dynamic_ratio fields 
- DiffSupress functions to supress the 'lb_dynmaic_ratio_preferred' when 'lb_preferred_method' is not 'DYNAMIC_RATIO' 
- DiffSupress functions to supress the 'lb_dynmaic_ratio_alternate' when 'lb_alternate_method' is not 'DYNAMIC_RATIO' and lb_preferred_method is TOPOLOGY
- Made changes to error message 
NPA -312 
- Added a diffsupress function to sort and compare the old and newlist for patterns and authzones
=> [FIX] --> NPA-299 , NPA-297 , NPA-312

go.mod, go.sum, infoblox/datasource_infoblox_dtc_lbdn.go, infoblox/datasource_infoblox_dtc_lbdn_test.go, infoblox/resource_infoblox_dtc_lbdn.go, infoblox/resource_infoblox_dtc_lbdn_test.go, vendor/github.com/infobloxopen/infoblox-go-client/v2/object_manager.go, vendor/github.com/infobloxopen/infoblox-go-client/v2/object_manager_dtc_lbdn.go, vendor/modules.txt
1. Modified auth_zones field from TypeList to Struct Type in LBDN resource and datasource.
2. Modified the test cases according to the changes above.
3. updated go.mod and vendor directory to use latest go-client.
=> NPA-308 Fix

go.mod, go.sum, infoblox/datasource_infoblox_dtc_lbdn.go, infoblox/datasource_infoblox_dtc_lbdn_test.go, infoblox/resource_infoblox_dtc_lbdn.go, infoblox/resource_infoblox_dtc_lbdn_test.go, vendor/github.com/infobloxopen/infoblox-go-client/v2/object_manager_dtc_lbdn.go, vendor/modules.txt
Updating AuthZone to have 1 view as per WAPI.
=> NPA-308: Fix changes

infoblox/provider.go, infoblox/resource_infoblox_dtc_lbdn.go, infoblox/resource_infoblox_dtc_pool.go
Added a common function to normalize and sort the list to Diffsuppress monitors  in DTC pool and patterns and auth_zones in DTC LDBN
=> Added a common function to normalize and sort the list to Diffsuppress

infoblox/resource_infoblox_dtc_pool.go
Updated Diffsupress function for consolidated_montiors field
added error checks in convertInterface to List function
=> Updated Diffsupress function for consolidated_montiors field

infoblox/resource_infoblox_dtc_pool_test.go, infoblox/resource_infoblox_dtc_server_test.go
added consolidated monitors test case
made changes in the compare function to compare the name instead of reference
=> updating DTC pool test cases 

infoblox/resource_infoblox_dtc_pool.go
updated consolidated_montiors in Create function
=> updated consolidated_montiors in Create function

docs/data-sources/infoblox_dtc_pool.md, docs/resources/infoblox_dtc_pool.md, examples/datasources/infoblox_dtc_pool.tf, examples/resources/infoblox_dtc_pool.tf
Documentation for DataSource and Resource for DTC pools
Examples for DTC Pools datasource and resource
=> Documentation for DataSource and Resource for DTC pools ,
